# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Extensions test
has_binder: false
has_settings: true
kind: frontend
labextension_name: extensionstest
project_short_description: A JupyterLab extension.
python_name: extensionstest
repository: https://github.com/romina1601/extensions-test
test: true

